version: '3.9'

services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    env_file:
      - .env

  myproject:
    build: .
    ports:
      - '80:80'
    depends_on:
      - postgres
    command: >
      bash -c "uvicorn main:app --host 0.0.0.0 --port 80"